name: Deploy to staging

on:
- pull_request

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build
        env:
          ELEVENTY_ENV: prod
        run: npm ci && npm run build

      - name: Configure gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.1
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_KEY }}

      - name: Determine staging deploy version
        run: node -e "console.log('::set-env name=GAE_VERSION::' + require('crypto').createHash('md5').update(process.argv[1]).digest('hex'))" $GITHUB_REF

      - name: Deploy via gcloud
        run: gcloud app deploy --quiet --project web-dev-staging --no-promote --version $GAE_VERSION

      - name: Check for 200
        uses: srt32/uptime@v0.1
        with:
          url-to-hit: https://${{ env.GAE_VERSION }}-dot-web-dev-staging.appspot.com

# TODO(samthor): Write generated hash to comment on PR.
